almaDataLinkServiceURI = ivo://almascience.org/datalink
almaRequestHandlerServiceURI = ivo://almascience.org/requesthandler
almaSODAServiceURI = ivo://almascience.org/soda
almaDataPortalServiceURI = ivo://almascience.org/dataportal
almaFileSodaServicePort = 8080
almaLoggingServiceURL = https://alma.kawfee.ca/logging/entry
almaTAPUploadByteLimit = 5242880
almaTAPUploadRowLimit = 5000
almaTAPUploadColumnLimit = 25